export const categories = [
  {
    id: 1,
    name: "Astrology",
    icon: "assets/icons/astrology.png",
  },
  {
    id: 2,
    name: "Assistant",
    icon: "assets/icons/assistant.png",
  },
  {
    id: 3,
    name: "Sports",
    icon: "assets/icons/sports.png",
  },
  {
    id: 4,
    name: "Photographer",
    icon: "assets/icons/film.png",
  },
  {
    id: 5,
    name: "Makeup",
    icon: "assets/icons/makeup.png",
  },
  {
    id: 6,
    name: "Mehndi",
    icon: "assets/icons/mehndi.png",
  },
  {
    id: 7,
    name: "Developing",
    icon: "assets/icons/developing.png",
  },
  {
    id: 8,
    name: "UI/UX",
    icon: "assets/icons/ui-ux.png",
  },
];

export const countryIsoCodes = {
  AG: "Antigua and Barbuda",
  AR: "Argentina",
  AM: "Armenia",
  AW: "Aruba",
  AU: "Australia",
  AT: "Austria",
  AZ: "Azerbaijan",
  BS: "Bahamas",
  BH: "Bahrain",
  BD: "Bangladesh",
  BB: "Barbados",
  BY: "Belarus",
  BE: "Belgium",
  BZ: "Belize",
  BJ: "Benin",
  BM: "Bermuda",
  BT: "Bhutan",
  BO: "Bolivia",
  CU: "Cuba",
  CW: "Curaçao",
  CY: "Cyprus",
  CZ: "Czech Republic",
  DK: "Denmark",
  DJ: "Djibouti",
  DM: "Dominica",
  DO: "Dominican Republic",
  EC: "Ecuador",
  EG: "Egypt",
  SV: "El Salvador",
  GQ: "Equatorial Guinea",
  ER: "Eritrea",
  EE: "Estonia",
  SZ: "Eswatini",
  ET: "Ethiopia",
};

export const data = [
  {
    id: 1,
    username: "Jules",
    country: "SV",
    avatar: "https://i.pravatar.cc/150?img=53",
    category: "Assistant",
  },
  {
    id: 2,
    username: "Helga",
    country: "CY",
    avatar: "https://i.pravatar.cc/150?img=3",
    category: "Astrology",
  },
  {
    id: 3,
    username: "Elfrieda",
    country: "EC",
    avatar: "https://i.pravatar.cc/150?img=62",
    category: "Mehndi",
  },
  {
    id: 4,
    username: "Chauncey",
    country: "CU",
    avatar: "https://i.pravatar.cc/150?img=9",
    category: "Photographer",
  },
  {
    id: 5,
    username: "Alysa",
    country: "DK",
    avatar: "https://i.pravatar.cc/150?img=7",
    category: "Photographer",
  },
  {
    id: 6,
    username: "Hilbert",
    country: "BZ",
    avatar: "https://i.pravatar.cc/150?img=16",
    category: "UI/UX",
  },
  {
    id: 7,
    username: "Leanna",
    country: "EC",
    avatar: "https://i.pravatar.cc/150?img=58",
    category: "Photographer",
  },
  {
    id: 8,
    username: "Diana",
    country: "CU",
    avatar: "https://i.pravatar.cc/150?img=4",
    category: "Assistant",
  },
  {
    id: 9,
    username: "Matilda",
    country: "DO",
    avatar: "https://i.pravatar.cc/150?img=54",
    category: "Makeup",
  },
  {
    id: 10,
    username: "Felicia",
    country: "GQ",
    avatar: "https://i.pravatar.cc/150?img=17",
    category: "Mehndi",
  },
  {
    id: 11,
    username: "Reece",
    country: "SZ",
    avatar: "https://i.pravatar.cc/150?img=47",
    category: "Makeup",
  },
  {
    id: 12,
    username: "Austen",
    country: "AR",
    avatar: "https://i.pravatar.cc/150?img=48",
    category: "Developing",
  },
  {
    id: 13,
    username: "Jannie",
    country: "CW",
    avatar: "https://i.pravatar.cc/150?img=57",
    category: "Developing",
  },
  {
    id: 14,
    username: "Donato",
    country: "BE",
    avatar: "https://i.pravatar.cc/150?img=48",
    category: "Makeup",
  },
  {
    id: 15,
    username: "Okey",
    country: "ET",
    avatar: "https://i.pravatar.cc/150?img=12",
    category: "Makeup",
  },
  {
    id: 16,
    username: "Jeff",
    country: "BT",
    avatar: "https://i.pravatar.cc/150?img=65",
    category: "Developing",
  },
  {
    id: 17,
    username: "Rebeka",
    country: "EG",
    avatar: "https://i.pravatar.cc/150?img=25",
    category: "Developing",
  },
  {
    id: 18,
    username: "Kenya",
    country: "SV",
    avatar: "https://i.pravatar.cc/150?img=56",
    category: "Photographer",
  },
  {
    id: 19,
    username: "Clyde",
    country: "DJ",
    avatar: "https://i.pravatar.cc/150?img=4",
    category: "Sports",
  },
  {
    id: 20,
    username: "Elisabeth",
    country: "DO",
    avatar: "https://i.pravatar.cc/150?img=52",
    category: "Mehndi",
  },
];
